creating single category component
sardorboboshov/budgetify-w1 pull request #11
Opened 2022-04-18 20:37 UTC by sardorboboshov

https://user-images.githubusercontent.com/89270394/163873881-1015aeba-e96e-476c-9f64-bd302e026286.mp4

I added updating functionality to category item. But when I change category title, it doesnt show updated version of category, but when I refresh the page, it shows edited version of category. How can I solve that problem?

2022-04-19 05:29 UTC, vokanred requested changes
FormControl is a source of truth

2022-04-19 05:29 UTC, vokanred commented on client/src/app/main/category/single-category/single-category.component.html
> +    <span>{{ category.title | titlecase }}</span>
You display category title but should display form control value

2022-04-19 05:29 UTC, vokanred commented on client/src/app/main/category/single-category/single-category.component.html
> +      [value]="category.title"
You shouldn't bind value when use formControlName

2022-04-19 05:29 UTC, vokanred commented on client/src/app/main/category/single-category/single-category.component.ts
> +    title: new FormControl({ value: '', disabled: !this.viewMode }, [
You should update this value on category change

2022-04-19 05:30 UTC, vokanred commented
![Screen Shot 2022-04-19 at 8 29 57 AM](https://user-images.githubusercontent.com/93642893/163926441-8b118856-5c95-4baf-bfc4-2548608015ce.png)
![Screen Shot 2022-04-19 at 8 30 12 AM](https://user-images.githubusercontent.com/93642893/163926466-c9c3a178-fa6f-4852-8d44-89d35cee8447.png)

2022-04-19 05:30 UTC, vokanred commented
Another solution is using template driven forms

2022-04-19 05:37 UTC, vokanred commented
And one more solution is to update category object using response from API.

2022-04-19 12:06 UTC, sardorboboshov commented
> And one more solution is to update category object using response from API.

It is working perfectly, thank you very much!

2022-04-20 05:51 UTC, vokanred approved these changes
Approved

2022-04-20 11:10 UTC, merged