first commit for 3rd week
sardorboboshov/budgetify-w1 pull request #3
Opened 2022-03-20 09:26 UTC by sardorboboshov

2022-03-21 06:45 UTC, vokanred requested changes

2022-03-21 06:45 UTC, vokanred commented on .env
> +MONGODB_URL=mongodb://localhost:27017/admin
Do you use MONGODB_URL and DB_NAME?

2022-03-21 06:45 UTC, vokanred commented on app.js
> -const passport = require('passport');
Why did you remove passport?

2022-03-21 06:56 UTC, vokanred commented on models/users.js
> +  email: {
You can add additional email validation here as well

2022-03-21 06:57 UTC, vokanred commented on controllers/authController.js
> +  const emailIsValid = (email) => /[a-zA-Z0-9]@[a-zA-Z0-9]/.test(email);
You can use any validation packages

2022-03-21 07:06 UTC, sardorboboshov commented on .env
> +MONGODB_URL=mongodb://localhost:27017/admin
Firstly I was using local mongoDB(and I was using MONGODB_URL and DB_NAME) and I switched to remote MongoDB and I forgot to delete those two variables in .env file. Should I delete them and open new pr or can I delete them in next hw?

2022-03-21 07:11 UTC, sardorboboshov commented on app.js
> -const passport = require('passport');
Using jwtCallback function(which was part of passport package) made some issues in application and it didnt run, so I removed that package. If it is required to use that package I will reinstall and use.

2022-03-21 07:14 UTC, sardorboboshov commented on models/users.js
> +  email: {
Should I do validation in both: middleware and schema? Or using validation in only one of them is enough?

2022-03-21 07:16 UTC, vokanred commented on models/users.js
> +  email: {
Validation in model layer is safer

2022-03-21 07:16 UTC, vokanred commented on .env
> +MONGODB_URL=mongodb://localhost:27017/admin
You can use connection string for a local db also.
Remove and create a new commit in the current branch (PR).

2022-03-21 07:18 UTC, vokanred commented on app.js
> -const passport = require('passport');
I thought  that it was your homework to use passport. Wasn't it?
You can ask how to fix such issues

2022-03-21 07:31 UTC, sardorboboshov commented on controllers/authController.js
> +  const emailIsValid = (email) => /[a-zA-Z0-9]@[a-zA-Z0-9]/.test(email);
But why to use additional packages for small things that can be solved by js itself? Should I use package for validation?

2022-03-21 07:44 UTC, vokanred commented on controllers/authController.js
> +  const emailIsValid = (email) => /[a-zA-Z0-9]@[a-zA-Z0-9]/.test(email);
Are you sure that you considered all possible cases?
For example I found this regex on stackoverflow.

(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\[(?:(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9]))\.){3}(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9])|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\])

Packages allow you not to think about such details

2022-03-21 09:06 UTC, sardorboboshov commented on .env
> +MONGODB_URL=mongodb://localhost:27017/admin
I created new commit:
1)removed 2 variables from .env file
2)installed "validator" package and used them to validate email
3)added validation to the schema for email
4)reinstalled passport and used them and there are no issues right now.

2022-03-24 09:56 UTC, vokanred commented on controllers/authController.js
> +  const emailIsValid = (email) => /[a-zA-Z0-9]@[a-zA-Z0-9]/.test(email);
Any news?

2022-03-24 10:15 UTC, vokanred commented on controllers/authController.js
> +  const emailIsValid = (email) => /[a-zA-Z0-9]@[a-zA-Z0-9]/.test(email);
What about `const emailIsValid = (email) => /[a-zA-Z0-9]@[a-zA-Z0-9]/.test(email);`?
You haven't replaced it with validator

2022-03-24 10:16 UTC, vokanred commented on controllers/authController.js
> +  const emailIsValid = (email) => /[a-zA-Z0-9]@[a-zA-Z0-9]/.test(email);
And request review again, because PR state now is Changes requested

2022-03-24 10:41 UTC, sardorboboshov commented on controllers/authController.js
> +  const emailIsValid = (email) => /[a-zA-Z0-9]@[a-zA-Z0-9]/.test(email);
> 

As I understand I should create new pull request right?

2022-03-24 10:46 UTC, sardorboboshov reviewed
Commit after 1st review

2022-03-24 10:48 UTC, vokanred approved these changes

2022-03-24 10:50 UTC, vokanred approved these changes
Done. Pls merge

2022-03-24 10:50 UTC, merged