adding authorization and backlog work from backend
sardorboboshov/budgetify-w1 pull request #6
Opened 2022-04-03 16:39 UTC by sardorboboshov

2022-04-04 13:56 UTC, vokanred requested changes
Pls review comments and feel free to ask questions

2022-04-04 13:56 UTC, vokanred commented on client/src/app/app-routing.module.ts
> +    redirectTo: 'login',
I think the correct flow is redirect to 'categories' and only if user is not authenticated redirect to login

2022-04-04 13:56 UTC, vokanred commented on client/src/app/auth/auth-form/auth-form.component.ts
> +      console.log('successful login');
Remove

2022-04-04 13:56 UTC, vokanred commented on client/src/app/auth/auth.interceptor.ts
> +      const jwt = localStorage.getItem('idToken');
Pls incapsulate auth implementation details in authService. Interceptor shouldn't know about how and where you store token

2022-04-04 13:56 UTC, vokanred commented on client/src/app/auth/auth.module.ts
> +    RouterModule.forChild(routes)
forChild is usually used for lazy loaded modules

2022-04-04 13:56 UTC, vokanred commented on client/src/app/auth/auth.module.ts
> +const routes: Routes = [
You've already defined this route in app routing

2022-04-04 13:56 UTC, vokanred commented on client/src/app/auth/services/auth.service.ts
> +    const expiresIn = localStorage.getItem('expiresIn');
I don't think that you should store expiresIn, because backend will return 401 when token is expired

2022-04-04 13:56 UTC, vokanred commented on client/src/app/auth/services/auth.service.ts
> +    const expiresIn = Date.now() + 60 * 60 * 1000;
You set expiration date on backend side
FE shouldn't know anything about token lifetime

2022-04-05 07:22 UTC, sardorboboshov commented on client/src/app/auth/services/auth.service.ts
> +    const expiresIn = localStorage.getItem('expiresIn');
Can you explain me how can I handle check is user loggedIn or not on frontend part and handle 401 error? Lecturer showed with setting expiresIn in localstorage and not showed how to handle errors. I am trying to find solution but I cannt find solution for that.

2022-04-05 08:32 UTC, sardorboboshov commented on client/src/app/app-routing.module.ts
> +    redirectTo: 'login',
I applied changes, if you not seeing them, please let me know

2022-04-06 07:11 UTC, vokanred commented
You can read about 401 handling here for example.
https://dev.to/ayeletdn/angular-http-interceptor-888

2022-04-06 07:12 UTC, vokanred commented
You've done a good job. Pls review my latest comments

2022-04-06 09:28 UTC, sardorboboshov commented
> You've done a good job. Pls review my latest comments

I have changed interceptor file. If you not seeing them, please let me know.

2022-04-07 05:35 UTC, vokanred approved these changes
Done. Think about redirection that I've suggested

2022-04-07 08:27 UTC, sardorboboshov commented
> Done. Think about redirection that I've suggested

Thanks understandable. I am gonna change that parts as you explained.

2022-04-07 08:29 UTC, sardorboboshov commented
> Done. Think about redirection that I've suggested

I cannt understans what do u mean by "auth logic". Can you explain me more about that?

2022-04-07 15:19 UTC, merged

2022-04-07 17:22 UTC, sardorboboshov commented on client/src/app/app-routing.module.ts
> +    redirectTo: 'login',
> App routing shouldn't depend on auth logic. I t's possible case that in future authorization can be disabled

As you said I changed redirectTo:'categories' and removed 'categories' from 29th line of code(2nd picture). But it made some problem.
When I didnt authorized and visited to the page it showed blank page, the reason for that,when we visit the page and if user not authorized yet, we again redirecting user to the same url(localhost:4200) and it creating infinite loop. So I didnt remove 'categories' from the 29th line and code working correctly.