layout assingment
sardorboboshov/budgetify-w1 pull request #7
Opened 2022-04-05 19:33 UTC by sardorboboshov

2022-04-11 04:52 UTC, vokanred requested changes
Pls review comments and make changes

2022-04-11 04:52 UTC, vokanred commented on .env
>  PORT=3000
Pls add the file to .gitignore

2022-04-11 04:52 UTC, vokanred commented on .env
>  PORT=3000
And remove from VCS

2022-04-11 04:52 UTC, vokanred commented on client/src/app/layout/header/header.component.html
> +  <div class="spacer"></div>
This is not a good solution. All spaces should be declared in styles only.

2022-04-11 04:52 UTC, vokanred commented on client/src/app/layout/header/header.component.html
> +  <span>Budgetify</span>
It's better to use a header tag here, e.g. h1

2022-04-11 04:52 UTC, vokanred commented on client/src/app/layout/header/header.component.html
> +  <div class="spacer"></div>
Pls remove this div

2022-04-11 04:52 UTC, vokanred commented on client/src/app/layout/header/header.component.html
> +  <button mat-button>Categories</button>
You can set `margin-left: auto` for this button and result will be the same without any extra divs

2022-04-11 04:52 UTC, vokanred commented on client/src/app/app-routing.module.ts
> +    redirectTo: 'login',
Main page should be opened by default

2022-04-11 04:52 UTC, vokanred commented on client/src/app/layout/header/header.component.html
> +  <button mat-button>Categories</button>
You're ready to add a link to categories

2022-04-11 04:52 UTC, vokanred commented on client/src/app/main/main-page/main-page.component.html
> +    <app-header></app-header>
Main page should have a content. You missed router-outlet between header and footer

2022-04-11 08:27 UTC, sardorboboshov commented on client/src/app/main/main-page/main-page.component.html
> +    <app-header></app-header>
> Main page should have a content. You missed router-outlet between header and footer

in that commit, i dont have content of main page yet, i added them in next commit as you said and used router-outlet:
https://github.com/sardorboboshov/budgetify-w1/blob/w6_l1/client/src/app/main/main.component.html. 
Can I skip that part for that pr review,because if I add app will be broken and I need to add and fix many things.

2022-04-11 08:56 UTC, sardorboboshov commented
> Pls review comments and make changes

I made changes, if you not seeing them, please let me know

2022-04-12 06:17 UTC, vokanred approved these changes
Done

2022-04-12 07:32 UTC, merged