W6 l1, added loader spinner, category page, improved main page
sardorboboshov/budgetify-w1 pull request #9
Opened 2022-04-10 19:47 UTC by sardorboboshov

2022-04-11 04:54 UTC, vokanred commented
What is this?

2022-04-11 08:31 UTC, sardorboboshov commented
> What is this?

pr for 1st homework of previous week.

2022-04-11 12:52 UTC, vokanred commented
Do you need the previous PR https://github.com/sardorboboshov/budgetify-w1/pull/7?
Or I should review only this?

2022-04-11 15:01 UTC, sardorboboshov commented
> Do you need the previous PR #7? Or I should review only this?

you can only review this too: it includes the 2nd home task of week5 and 1st home task of 6th week.

2022-04-11 15:02 UTC, sardorboboshov commented
> > Do you need the previous PR #7? Or I should review only this?
> 
> you can only review this too: it includes the 2nd home task of week5 and 1st home task of 6th week(previous week)

2022-04-12 06:34 UTC, vokanred commented
Pls merge the previous PR and update this branch. Then I'll review

2022-04-12 12:18 UTC, vokanred commented
You should merge master branch to this branch

2022-04-12 14:38 UTC, sardorboboshov commented
> You should merge master branch to this branch

I kinda didnt understand that, should I open a new PR comparing that branch with master branch?

2022-04-12 17:19 UTC, vokanred commented
Switch locally to w6_l1. Then `git pull origin master`. Then resolve conflicts. And then push changes `git push origin w6_l1`

2022-04-12 18:22 UTC, sardorboboshov commented
> Switch locally to w6_l1. Then `git pull origin master`. Then resolve conflicts. And then push changes `git push origin w6_l1`.
> 
> Now w6_l1 doesn't have actual code from master.

Thanks for the guidance. I did exactly as you said, if something is wrong, please let me know

2022-04-14 14:56 UTC, sardorboboshov commented
> Thanks for the guidance. I did exactly as you said, if something is wrong, please let me know

Thanks for the guidance. I did exactly as you said, if something is wrong, please let me know

2022-04-14 19:08 UTC, vokanred requested changes
Nice.
Pls review comments and make changes

2022-04-14 19:08 UTC, vokanred commented on client/src/app/main/accounts/accounts.component.ts
> +    this.accountIdx.emit(this.selectedAccountIdx);
It's strange to emit in ngOnInit(). Why do you need this?

If you really need it just decorate  selectedAccountIdx: number = 0; as @Input and pass initial value from parent.
But I think it's not necessary.

2022-04-14 19:08 UTC, vokanred commented on client/src/app/main/transactions/transactions.component.html
> +<section class="wrapper">
I think this component should be split into smaller components

2022-04-14 19:08 UTC, vokanred commented on client/src/app/main/transactions/transactions.component.ts
> +    this.mainService
async pipe or unsubscribe

2022-04-14 19:08 UTC, vokanred commented on client/src/app/main/transactions/transactions.component.ts
> +    this.mainService
async pipe or unsubscribe

2022-04-14 19:08 UTC, vokanred commented on client/src/app/main/transactions/transactions.component.ts
> +    this.mainService
async pipe or unsubscribe

2022-04-14 19:08 UTC, vokanred commented on client/src/app/shared/services/spinner.service.ts
> +      .pipe(observeOn(asyncScheduler));
Did lector show you asyncScheduler?

2022-04-14 19:08 UTC, vokanred commented on controllers/categoryController.js
> +      if (category_.title.toLowerCase() === title) {
You shouldn't check this manually in code.

Just add unique: true to your model and mongoose will throw error
![Screen Shot 2022-04-14 at 10 06 11 PM](https://user-images.githubusercontent.com/93642893/163459332-0dda44e7-dbbe-462d-86fc-15ced8da8697.png)
.

2022-04-14 19:08 UTC, vokanred commented on controllers/categoryController.js
> +      if (category_.title.toLowerCase() === title) {
I see that you've already added it. So you can remove this check

2022-04-14 22:51 UTC, sardorboboshov commented on client/src/app/layout/header/header.component.ts
> +    this.mainService.getData(Number(user_id)).subscribe((data: any) => {
![image](https://user-images.githubusercontent.com/89270394/163490037-413b5a5e-69a7-4d0f-b432-5c8a417c7580.png)
![image](https://user-images.githubusercontent.com/89270394/163490130-63bd5a46-ce12-433f-bedd-054ae142c51e.png)

username is not being displayed, also there is no "it is running" showing on the console.
can you give some advice how can I use async pipe here

2022-04-15 08:25 UTC, sardorboboshov commented on client/src/app/shared/services/spinner.service.ts
> +      .pipe(observeOn(asyncScheduler));
> Did lector show you asyncScheduler?

yes

2022-04-15 08:42 UTC, sardorboboshov commented on client/src/app/main/transactions/transactions.component.ts
> +    this.mainService
> async pipe or unsubscribe

if i use async pipe for currency and use that in template it is giving me that error:
![image](https://user-images.githubusercontent.com/89270394/163548175-02587666-9588-412e-955c-17a22f8289a2.png)
![image](https://user-images.githubusercontent.com/89270394/163548214-19aef4f6-aacd-4012-be0e-92916764feec.png)

2022-04-15 08:45 UTC, sardorboboshov commented on client/src/app/main/transactions/transactions.component.ts
> +    this.mainService
> async pipe or unsubscribe

if i use async pipe I can only display transactions on page and I wont be able to access that on .ts file therefore I cannt filter transactions according to types of transactions. What do u suggest me in that case?

2022-04-15 11:01 UTC, sardorboboshov commented
> Nice. Pls review comments and make changes

I commited changes according to your feedbacks. 
1)Used pipe - async apart from transaction components where I needed to access and filter data
2)Unsubscribed on transaction component
3)Splitted transaction component into two component
4)Resolved .gitignore file, removed checking on creating category.
If you not seeing them or in the case of any error, please let me know.

2022-04-15 17:57 UTC, vokanred commented on client/src/app/main/accounts/accounts.component.ts
> +    this.mainService
this.accounts$ = this.mainService.getAllAccountsData(Number(user_id))

2022-04-15 17:57 UTC, vokanred commented on client/src/app/main/category/category.component.ts
> +    this.mainService.getAllCategories().pipe((res) => (this.categories$ = res));
this.categories$ = this.mainService.getAllCategories()

2022-04-15 17:59 UTC, vokanred requested changes
Almost done. Just fix all places where you've added async pipe.
I've written couple example how it should look

2022-04-15 19:04 UTC, sardorboboshov commented
> Almost done. Just fix all places where you've added async pipe. I've written couple example how it should look

fixed all places where async pipe is used. if you not seeing them, please let me know.

2022-04-17 11:47 UTC, vokanred approved these changes
Approved

2022-04-17 13:55 UTC, merged